try to fix the curl

diff --git a/Dockerfile.dapper b/Dockerfile.dapper
--- a/Dockerfile.dapper
+++ b/Dockerfile.dapper
@@ -1,5 +1,6 @@
-FROM registry.suse.com/bci/golang:1.21
+FROM registry.suse.com/bci/golang:1.21 as base
 
+# Set environment variables and install dependencies as before
 ARG DAPPER_HOST_ARCH
 ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}
 ENV CATTLE_HELM_VERSION v2.16.8-rancher2
@@ -22,7 +23,13 @@ RUN zypper install -y -f docker && rpm -e --nodeps --noscripts containerd
 # prevents `detected dubious ownership in repository` git error due to uid/gid not matching when using bind mounts
 RUN git config -f /etc/gitconfig --add safe.directory /go/src/github.com/rancher/rancher
 
-RUN curl -sLf https://github.com/rancher/machine/releases/download/${CATTLE_MACHINE_VERSION}/rancher-machine-${ARCH}.tar.gz | tar xvzf - -C /usr/bin
+# Debugging: Print the value of ARCH
+RUN echo "ARCH is set to: ${ARCH}"
+
+# Fixing the URL for rancher-machine download
+RUN curl -sLf https://github.com/rancher/machine/releases/download/${CATTLE_MACHINE_VERSION}/rancher-machine-${ARCH}.tar.gz | tar xvzf - -C /usr/bin || \
+    (echo "Failed to download rancher-machine-${ARCH}.tar.gz"; exit 1)
+
 RUN if [ "${ARCH}" != "s390x" ]; then \
         curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=${K3D_VERSION} bash; \
     fi
@@ -85,7 +92,7 @@ COPY --from=rancher/k3s:v1.28.6-k3s2 \
     /bin/runc \
     /bin/which \
     /bin/aux/xtables-legacy-multi \
-    /usr/bin/
+/usr/bin/
 
 RUN mkdir -p /go/src/github.com/rancher/rancher/.kube
 
@@ -111,7 +118,6 @@ RUN ln -s /usr/bin/cni /usr/bin/bridge && \
     ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables-translate && \
     ln -s /etc/rancher/k3s/k3s.yaml /go/src/github.com/rancher/rancher/.kube/k3s.yaml
 
-
 RUN curl -sLf https://github.com/rancher/k3s/releases/download/${CATTLE_K3S_VERSION}/k3s-images.txt -o /usr/tmp/k3s-images.txt
 
 # Python related dependencies for the Integration/Validation tests.
@@ -133,12 +139,13 @@ RUN if [ "${ARCH}" == "amd64" ]; then \
         helm_v3 plugin install https://github.com/helm-unittest/helm-unittest.git --version ${HELM_UNITTEST_VERSION}; \
     fi
 
+# Copy the rancher binary from the official Rancher image
+#COPY --from=rancher/rancher:v2.8-head /usr/bin/rancher /go/src/github.com/rancher/rancher/bin/rancher
+COPY --from=rancher/rancher:v2.8-head /usr/bin/rancher bin/rancher
 
 VOLUME /var/lib/rancher
 VOLUME /var/lib/kubelet
 WORKDIR ${DAPPER_SOURCE}
-
-COPY --from=rancher/rancher:v2.8-head /usr/bin/rancher bin/rancher
 
 ENTRYPOINT ["./scripts/entry"]
 CMD ["ci"]
