new commit from israel gomez.

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -37,17 +37,17 @@ export CATTLE_FEATURES="harvester=false"
 # Moby License Apache 2.0: https://github.com/moby/moby/blob/ed89041433a031cafc0a0f19cfe573c31688d377/LICENSE                           #
 #########################################################################################################################################
 # only run this if rancher is not running in kubernetes cluster
-if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
-  # move the processes from the root group to the /init group,
-  # otherwise writing subtree_control fails with EBUSY.
-  mkdir -p /sys/fs/cgroup/init
-  xargs -rn1 < /sys/fs/cgroup/cgroup.procs > /sys/fs/cgroup/init/cgroup.procs || :
-  # enable controllers
-  sed -e 's/ / +/g' -e 's/^/+/' <"/sys/fs/cgroup/cgroup.controllers" >"/sys/fs/cgroup/cgroup.subtree_control"
-fi
+# if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
+#   # move the processes from the root group to the /init group,
+#   # otherwise writing subtree_control fails with EBUSY.
+#   mkdir -p /sys/fs/cgroup/init
+#   xargs -rn1 < /sys/fs/cgroup/cgroup.procs > /sys/fs/cgroup/init/cgroup.procs || :
+#   # enable controllers
+#   sed -e 's/ / +/g' -e 's/^/+/' <"/sys/fs/cgroup/cgroup.controllers" >"/sys/fs/cgroup/cgroup.subtree_control"
+# fi
 
 echo "docker run -d --name rancher-server --restart=unless-stopped --privileged -p 6443:443 -p 8080:80 -e CATTLE_BOOTSTRAP_PASSWORD="admin" $IMAGE"
-docker run -d --name rancher-server --restart=unless-stopped --privileged -p 6443:443 -p 8080:80 -e CATTLE_BOOTSTRAP_PASSWORD="admin" $IMAGE
+docker run -d --name rancher-server --restart=unless-stopped --privileged -p 6443:6443 -p 8080:8080 -p 443:443 -e CATTLE_BOOTSTRAP_PASSWORD="admin" -e CATTLE_DEV_MODE=yes $IMAGE
 
 sleep 5
 
