Work done by Rafael Breno and Israel Gomez.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -22,8 +22,10 @@ fi
 
 cd $(dirname $0)/..
 
-echo Running unit tests
-# go test -cover -tags=test ./pkg/...
+echo "PWD $(pwd)"
+
+#echo Running unit tests
+#go test -cover -tags=test ./pkg/...
 
 if [ ${ARCH} == arm64 ] || [ ${ARCH} == s390x ]; then
     export ETCD_UNSUPPORTED_ARCH=${ARCH}
@@ -73,6 +75,8 @@ fi
 echo Starting rancher server for test
 touch /tmp/rancher.log
 
+export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
+
 mkdir -p /var/lib/rancher/$DIST/agent/images
 grep PodTestImage ./tests/v2prov/defaults/defaults.go | cut -f2 -d'"' > /var/lib/rancher/$DIST/agent/images/pull.txt
 grep MachineProvisionImage ./pkg/settings/setting.go | cut -f4 -d'"' >> /var/lib/rancher/$DIST/agent/images/pull.txt
@@ -90,7 +94,7 @@ run_rancher()
             dump_rancher_logs
             echo K3s logs were:
             echo -e "-----K3S-LOG-DUMP-START-----"
-            cat build/testdata/k3s.log | gzip | base64 -w 0
+            cat build/testdata/k3s.log
             echo -e "\n-----K3S-LOG-DUMP-END-----"
             set +e
             echo Attempting to kill K3s
@@ -117,7 +121,7 @@ dump_rancher_logs()
 {
   echo Rancher logs were
   echo -e "-----RANCHER-LOG-DUMP-START-----"
-  cat /tmp/rancher.log | gzip | base64 -w 0
+  cat /tmp/rancher.log
   echo -e "\n-----RANCHER-LOG-DUMP-END-----"
 }
 
@@ -130,12 +134,15 @@ trap "exit 1" 42
 PWRAPPROC="$$"
 
 PID=-1
+echo "----------- BEFORE"
 run_rancher &
+sleep 7
+echo "----------- AFTER"
 RANCHER_RUN_PID=$!
-trap cleanup exit
+#trap cleanup exit
 
-echo "Waiting for Rancher to be healthy"
-./scripts/retry --sleep 2 "curl -sf -o /dev/null http://localhost:8080/ping"
+# echo "Waiting for Rancher to be healthy"
+# ./scripts/retry --sleep 2 "curl -sf -o /dev/null http://localhost:8080/ping"
 
 echo "Waiting up to 5 minutes for rancher-webhook deployment"
 ./scripts/retry \
@@ -143,7 +150,9 @@ echo "Waiting up to 5 minutes for rancher-webhook deployment"
   --sleep 2 `# Sleep for 2 seconds in between attempts` \
   --message-interval 30 `# Print the progress message below every 30 attempts (roughly every minute)` \
   --message "rancher-webhook was not available after {{elapsed}} seconds" `# Print this progress message` \
-  "kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml rollout status -w -n cattle-system deploy/rancher-webhook &>/dev/null"
+  "kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml rollout status -w -n cattle-system deploy/rancher-webhook &"
+
+echo "-------------- 1 ------------------"
 
 echo "Waiting up to 5 minutes for rancher-provisioning-capi deployment"
 ./scripts/retry \
@@ -151,25 +160,34 @@ echo "Waiting up to 5 minutes for rancher-provisioning-capi deployment"
   --sleep 2 `# Sleep for 2 seconds in between attempts` \
   --message-interval 30 `# Print the progress message below every 30 attempts (roughly every minute)` \
   --message "rancher-provisioning-capi was not available after {{elapsed}} seconds" `# Print this progress message` \
-  "kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml rollout status -w -n cattle-provisioning-capi-system deploy/capi-controller-manager &>/dev/null"
+  "kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml rollout status -w -n cattle-provisioning-capi-system deploy/capi-controller-manager &"
+
+echo "-------------- 2 ------------------"
+
+echo "Sleeping for 20"
+sleep 20
+
+echo "Printing current kubectl thingies"
+kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml  get deployments --all-namespaces -o custom-columns=Namespace:.metadata.namespace,Name:.metadata.name,Replicas:.spec.replicas,Available:.status.availableReplicas
+kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml  get pods --all-namespaces -o custom-columns=Namespace:.metadata.namespace,Name:.metadata.name,Status:.status.phase,Node:.spec.nodeName
 
 #kill $TPID
 
-echo Running build-integration-setup
-./tests/v2/integration/scripts/build-integration-setup
+# echo Running build-integration-setup
+# ./tests/v2/integration/scripts/build-integration-setup
 
-echo Running integrationsetup
-export CATTLE_TEST_CONFIG=$(pwd)/config.yaml # used by integration tests and test setup
-./tests/v2/integration/bin/integrationsetup || {
-  dump_rancher_logs
-  exit 1
-}
+# echo Running integrationsetup
+# export CATTLE_TEST_CONFIG=$(pwd)/config.yaml # used by integration tests and test setup
+# ./tests/v2/integration/bin/integrationsetup || {
+#   dump_rancher_logs
+#   exit 1
+# }
 
-echo Running go integration tests
-go test -v -failfast -p 1 ./tests/v2/integration/... || {
-  dump_rancher_logs
-  exit 1
-}
+# echo Running go integration tests
+# go test -v -failfast -p 1 ./tests/v2/integration/... || {
+#   dump_rancher_logs
+#   exit 1
+# }
 
 echo Running tox tests
 INT_TESTS_STARTED=true
