python test.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -173,21 +173,21 @@ kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml  get pods --all-namespaces -o cus
 
 #kill $TPID
 
-echo Running build-integration-setup
-./tests/v2/integration/scripts/build-integration-setup
+# echo Running build-integration-setup
+# ./tests/v2/integration/scripts/build-integration-setup
 
-echo Running integrationsetup
-export CATTLE_TEST_CONFIG=$(pwd)/config.yaml # used by integration tests and test setup
-./tests/v2/integration/bin/integrationsetup || {
-  dump_rancher_logs
-  exit 1
-}
+# echo Running integrationsetup
+# export CATTLE_TEST_CONFIG=$(pwd)/config.yaml # used by integration tests and test setup
+# ./tests/v2/integration/bin/integrationsetup || {
+#   dump_rancher_logs
+#   exit 1
+# }
 
-echo Running go integration tests
-go test -v -failfast -p 1 ./tests/v2/integration/... || {
-  dump_rancher_logs
-  exit 1
-}
+# echo Running go integration tests
+# go test -v -failfast -p 1 ./tests/v2/integration/... || {
+#   dump_rancher_logs
+#   exit 1
+# }
 
 echo Running tox tests
 INT_TESTS_STARTED=true
